### ISSUE TITLE
Make release on forge

### ISSUE THREAD

**Issue by siebrand** [voxpupuli/puppet-swap_file#7]
I'm really happy that this module has been updated and got love.

What's needed to make a release on https://forge.puppet.com of this module?

**Comment by siebrand** [comment]
What’s blocking this?

**Comment by sahaqaa** [comment]
Also waiting for this module to be released to Puppet Forge :+1:

**Comment by kenyon** [comment]
I think we need #10 and #3 at least for a release.

**Comment by rwaffen** [comment]
Release will be done with #14

**Comment by rwaffen** [comment]
5.0.0 release is out... many thanks to @traylenator
